---
# otherwise
otherwise:
  controller: otherwise
  priority: -1000 # otherwise с очень низким приоритетом

# actions
home:
  path: /
  controller: mainPage
  openApi: home # ссылка на индификатор openAPI декларации

main2:
  path: /page2/
  methods: GET
  controller: mainPage2
  openApi: id2

hello:
  path: /hello/{name}/
  controller: hello